name: kitchen_inventory_app
description: A new Flutter project for kitchen inventory with Firebase
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  firebase_auth: ^4.16.0

  # Image picker for user uploads
  image_picker: ^1.1.1

  # UI & Utils
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/ready-for-app.csv
    - assets/images/groups/cook.png
    - assets/images/groups/clean.png
    - assets/images/groups/tools.png
    - assets/images/groups/health.png
