name: kitchen_inventory_app
description: A new Flutter project for kitchen inventory with Firebase
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase core (مطلوب لأي خدمة Firebase)
  firebase_core: ^2.32.0

  # Authentication
  firebase_auth: ^4.16.0

  # Firestore database
  cloud_firestore: ^4.17.5

  # Firebase storage
  firebase_storage: ^11.7.7

  # Google Sign-In (مطلوب للـ iOS إذا تبي تسجيل دخول بحساب Google)
  google_sign_in: ^6.2.1

  # باقي الحزم اللي تستخدمها
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/ready-for-app.csv
    - assets/images/groups/cook.png
    - assets/images/groups/clean.png
    - assets/images/groups/tools.png
    - assets/images/groups/health.png
