// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQLHxOO4PIEzGvgCiDr5iWkqBcwGYUdnU',
    appId: '1:251909397675:web:16c70f8f553888073cabee',
    messagingSenderId: '251909397675',
    projectId: 'kitchen-inventory-ad6f0',
    authDomain: 'kitchen-inventory-ad6f0.firebaseapp.com',
    storageBucket: 'kitchen-inventory-ad6f0.firebasestorage.app',
    measurementId: 'G-FBWMBHKKDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxSMSWysVbXdsbuBwTdK8r6e3I2TaSrNs',
    appId: '1:251909397675:android:4605bc0411a339ee3cabee',
    messagingSenderId: '251909397675',
    projectId: 'kitchen-inventory-ad6f0',
    storageBucket: 'kitchen-inventory-ad6f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQPjh6T0jVuHhZhMrqjzh81D2M7jk7mZo',
    appId: '1:251909397675:ios:279fd1674ec942e83cabee',
    messagingSenderId: '251909397675',
    projectId: 'kitchen-inventory-ad6f0',
    storageBucket: 'kitchen-inventory-ad6f0.firebasestorage.app',
    iosBundleId: 'com.ghafli78.kitcheninventory',
  );

}